import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'framer-motion';
import { COURSE_CATEGORIES } from '../../constants/categories';
import { Button } from '../../components/common';
import { Navbar } from '../../components/layout/Navbar';
import { Footer } from '../../components/layout/Footer';
export const HomePage = () => {
    return (_jsxs("div", { className: "min-h-screen bg-client-bg text-white", children: [_jsx(Navbar, {}), _jsxs("section", { className: "max-w-6xl mx-auto px-4 py-20 grid gap-12 lg:grid-cols-[1.1fr,0.9fr] items-center", children: [_jsxs("div", { children: [_jsx("p", { className: "text-client-secondary text-sm uppercase tracking-[0.5em] mb-6", children: "Premium Learning" }), _jsx("h1", { className: "text-5xl md:text-6xl font-heading leading-[1.05] mb-6", children: "LearnSphere empowers creators to launch immersive academies." }), _jsx("p", { className: "text-white/70 text-lg mb-10 max-w-2xl", children: "A flagship LMS engineered for high-converting funnels, cinematic content delivery, and enterprise-grade analytics." }), _jsxs("div", { className: "flex flex-wrap gap-4", children: [_jsx(Button, { variant: "primary", children: "Explore Courses" }), _jsx(Button, { variant: "outline", children: "Watch Demo" })] })] }), _jsxs(motion.div, { className: "rounded-3xl border border-white/10 bg-gradient-to-br from-client-primary/30 to-client-secondary/20 p-8 shadow-glow", initial: { opacity: 0, y: 30 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.6 }, children: [_jsx("p", { className: "uppercase text-xs tracking-[0.5em] text-white/70 mb-4", children: "Live Metrics" }), _jsx("div", { className: "grid grid-cols-2 gap-6", children: [
                                    { label: 'Learners', value: '128K' },
                                    { label: 'Courses', value: '1.2K' },
                                    { label: 'Instructors', value: '640' },
                                    { label: 'Avg Rating', value: '4.9/5' },
                                ].map((metric) => (_jsxs("div", { className: "rounded-2xl border border-white/10 bg-black/30 p-5", children: [_jsx("p", { className: "text-sm text-white/60", children: metric.label }), _jsx("p", { className: "text-3xl font-heading", children: metric.value })] }, metric.label))) })] })] }), _jsxs("section", { className: "max-w-6xl mx-auto px-4 pb-20", children: [_jsxs("div", { className: "flex items-center justify-between mb-8", children: [_jsx("h2", { className: "text-3xl font-heading", children: "Trending Categories" }), _jsx("p", { className: "text-white/60", children: "Curated clusters with cinematic hover cards." })] }), _jsx("div", { className: "grid gap-4 sm:grid-cols-2 lg:grid-cols-4", children: COURSE_CATEGORIES.map((category) => (_jsxs(motion.div, { whileHover: { y: -6, scale: 1.01 }, className: "rounded-3xl border border-white/10 bg-white/5 p-6", children: [_jsx("div", { className: "text-4xl mb-4", children: category.icon }), _jsx("p", { className: "text-xl font-heading", children: category.label }), _jsxs("p", { className: "text-white/50", children: [category.courses, " programs"] })] }, category.id))) })] }), _jsx("div", { className: "max-w-6xl mx-auto px-4", children: _jsx(Footer, {}) })] }));
};
