import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { lazy } from 'react';
import { BrowserRouter, Route, Routes } from 'react-router-dom';
import { ProtectedRoute } from './ProtectedRoute';
const HomePage = lazy(() => import('../pages/client/Home').then((module) => ({ default: module.HomePage })));
const CatalogPage = lazy(() => import('../pages/client/Catalog').then((module) => ({ default: module.CatalogPage })));
const CourseDetailPage = lazy(() => import('../pages/client/CourseDetail').then((module) => ({ default: module.CourseDetailPage })));
const PlayerPage = lazy(() => import('../pages/client/Player').then((module) => ({ default: module.PlayerPage })));
const MyLearningPage = lazy(() => import('../pages/client/MyLearning').then((module) => ({ default: module.MyLearningPage })));
const CartPage = lazy(() => import('../pages/client/Cart').then((module) => ({ default: module.CartPage })));
const CheckoutPage = lazy(() => import('../pages/client/Checkout').then((module) => ({ default: module.CheckoutPage })));
const LoginPage = lazy(() => import('../pages/client/Login').then((module) => ({ default: module.LoginPage })));
const RegisterPage = lazy(() => import('../pages/client/Register').then((module) => ({ default: module.RegisterPage })));
const ForgotPasswordPage = lazy(() => import('../pages/client/ForgotPassword').then((module) => ({ default: module.ForgotPasswordPage })));
const ResetPasswordPage = lazy(() => import('../pages/client/ResetPassword').then((module) => ({ default: module.ResetPasswordPage })));
const AdminLoginPage = lazy(() => import('../pages/admin/AdminLogin').then((module) => ({ default: module.AdminLoginPage })));
const AdminDashboardPage = lazy(() => import('../pages/admin/AdminDashboard').then((module) => ({ default: module.AdminDashboardPage })));
const AdminStudentsPage = lazy(() => import('../pages/admin/Students').then((module) => ({ default: module.AdminStudentsPage })));
const AdminInstructorsPage = lazy(() => import('../pages/admin/Instructors').then((module) => ({ default: module.AdminInstructorsPage })));
const AdminCoursesPage = lazy(() => import('../pages/admin/Courses').then((module) => ({ default: module.AdminCoursesPage })));
const AdminApprovalsPage = lazy(() => import('../pages/admin/Approvals').then((module) => ({ default: module.AdminApprovalsPage })));
const AdminRevenuePage = lazy(() => import('../pages/admin/Revenue').then((module) => ({ default: module.AdminRevenuePage })));
const AdminPayoutsPage = lazy(() => import('../pages/admin/Payouts').then((module) => ({ default: module.AdminPayoutsPage })));
const AdminCouponsPage = lazy(() => import('../pages/admin/Coupons').then((module) => ({ default: module.AdminCouponsPage })));
const AdminSettingsPage = lazy(() => import('../pages/admin/Settings').then((module) => ({ default: module.AdminSettingsPage })));
const AdminRolesPage = lazy(() => import('../pages/admin/Roles').then((module) => ({ default: module.AdminRolesPage })));
const AdminAuditLogsPage = lazy(() => import('../pages/admin/AuditLogs').then((module) => ({ default: module.AdminAuditLogsPage })));
const InstructorLoginPage = lazy(() => import('../pages/instructor/InstructorLogin').then((module) => ({ default: module.InstructorLoginPage })));
const InstructorOverviewPage = lazy(() => import('../pages/instructor/Overview').then((module) => ({ default: module.InstructorOverviewPage })));
const InstructorCoursesPage = lazy(() => import('../pages/instructor/MyCourses').then((module) => ({ default: module.InstructorCoursesPage })));
const InstructorCourseBuilderPage = lazy(() => import('../pages/instructor/CourseBuilder').then((module) => ({ default: module.InstructorCourseBuilderPage })));
const InstructorStudentsPage = lazy(() => import('../pages/instructor/Students').then((module) => ({ default: module.InstructorStudentsPage })));
const InstructorQnAPage = lazy(() => import('../pages/instructor/QnA').then((module) => ({ default: module.InstructorQnAPage })));
const InstructorReviewsPage = lazy(() => import('../pages/instructor/Reviews').then((module) => ({ default: module.InstructorReviewsPage })));
const InstructorRevenuePage = lazy(() => import('../pages/instructor/Revenue').then((module) => ({ default: module.InstructorRevenuePage })));
const InstructorProfilePage = lazy(() => import('../pages/instructor/Profile').then((module) => ({ default: module.InstructorProfilePage })));
const InstructorAnnouncementsPage = lazy(() => import('../pages/instructor/Announcements').then((module) => ({ default: module.InstructorAnnouncementsPage })));
const InstructorNotificationsPage = lazy(() => import('../pages/instructor/Notifications').then((module) => ({ default: module.InstructorNotificationsPage })));
const NotFoundPage = lazy(() => import('../pages/common/NotFound').then((module) => ({ default: module.NotFoundPage })));
export const AppRouter = () => {
    return (_jsx(BrowserRouter, { children: _jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(HomePage, {}) }), _jsx(Route, { path: "/courses", element: _jsx(CatalogPage, {}) }), _jsx(Route, { path: "/courses/:slug", element: _jsx(CourseDetailPage, {}) }), _jsx(Route, { path: "/login", element: _jsx(LoginPage, {}) }), _jsx(Route, { path: "/register", element: _jsx(RegisterPage, {}) }), _jsx(Route, { path: "/forgot-password", element: _jsx(ForgotPasswordPage, {}) }), _jsx(Route, { path: "/reset-password/:token", element: _jsx(ResetPasswordPage, {}) }), _jsxs(Route, { element: _jsx(ProtectedRoute, { role: "student" }), children: [_jsx(Route, { path: "/dashboard/student", element: _jsx(MyLearningPage, {}) }), _jsx(Route, { path: "/learn/:courseId/:lessonId", element: _jsx(PlayerPage, {}) }), _jsx(Route, { path: "/cart", element: _jsx(CartPage, {}) }), _jsx(Route, { path: "/checkout", element: _jsx(CheckoutPage, {}) })] }), _jsx(Route, { path: "/admin/login", element: _jsx(AdminLoginPage, {}) }), _jsxs(Route, { element: _jsx(ProtectedRoute, { role: "admin", redirectTo: "/admin/login" }), children: [_jsx(Route, { path: "/admin/dashboard", element: _jsx(AdminDashboardPage, {}) }), _jsx(Route, { path: "/admin/students", element: _jsx(AdminStudentsPage, {}) }), _jsx(Route, { path: "/admin/instructors", element: _jsx(AdminInstructorsPage, {}) }), _jsx(Route, { path: "/admin/courses", element: _jsx(AdminCoursesPage, {}) }), _jsx(Route, { path: "/admin/approvals", element: _jsx(AdminApprovalsPage, {}) }), _jsx(Route, { path: "/admin/revenue", element: _jsx(AdminRevenuePage, {}) }), _jsx(Route, { path: "/admin/payouts", element: _jsx(AdminPayoutsPage, {}) }), _jsx(Route, { path: "/admin/coupons", element: _jsx(AdminCouponsPage, {}) }), _jsx(Route, { path: "/admin/settings", element: _jsx(AdminSettingsPage, {}) }), _jsx(Route, { path: "/admin/roles", element: _jsx(AdminRolesPage, {}) }), _jsx(Route, { path: "/admin/logs", element: _jsx(AdminAuditLogsPage, {}) })] }), _jsx(Route, { path: "/instructor/login", element: _jsx(InstructorLoginPage, {}) }), _jsxs(Route, { element: _jsx(ProtectedRoute, { role: "instructor", redirectTo: "/instructor/login" }), children: [_jsx(Route, { path: "/instructor/overview", element: _jsx(InstructorOverviewPage, {}) }), _jsx(Route, { path: "/instructor/courses", element: _jsx(InstructorCoursesPage, {}) }), _jsx(Route, { path: "/instructor/courses/new", element: _jsx(InstructorCourseBuilderPage, {}) }), _jsx(Route, { path: "/instructor/courses/:id/edit", element: _jsx(InstructorCourseBuilderPage, {}) }), _jsx(Route, { path: "/instructor/students", element: _jsx(InstructorStudentsPage, {}) }), _jsx(Route, { path: "/instructor/qa", element: _jsx(InstructorQnAPage, {}) }), _jsx(Route, { path: "/instructor/reviews", element: _jsx(InstructorReviewsPage, {}) }), _jsx(Route, { path: "/instructor/revenue", element: _jsx(InstructorRevenuePage, {}) }), _jsx(Route, { path: "/instructor/profile", element: _jsx(InstructorProfilePage, {}) }), _jsx(Route, { path: "/instructor/announcements", element: _jsx(InstructorAnnouncementsPage, {}) }), _jsx(Route, { path: "/instructor/notifications", element: _jsx(InstructorNotificationsPage, {}) })] }), _jsx(Route, { path: "*", element: _jsx(NotFoundPage, {}) })] }) }));
};
